const menuBtn = document.getElementById("hamburger");
const navLinks = document.getElementById("navLinks");
const links = navLinks.querySelector("a")

menuBtn.addEventListener("click",()=>{
  navLinks.classList.toggle("active");
  if(navLinks.classList.contains("active")){
    menuBtn.innerHTML = "X";
    menuBtn.setAttribute("aria-expanded", "true")
  } else{menuBtn.innerHTML ="=";
    menuBtn.setAttribute("aria-expanded",
      "false"
    )
  }
})

links.forEach(links =>{
  links.addEventListener("click", () =>{
    navLinks.classList.remove("active");
    menuBtn.innerHTML = "=";
    menuBtn.setAttribute("aria-expanded",
    "false");
  })
})


// Objeto con ramales y sus paradas
const paradas = {
  "239p": [
    "Est. Banfield",
    "Maipú y Alsina",
    "Maipú y Pueyrredón",
    "Maipú y Arenales",
    "Maipú y Palacios",
    "Maipú y Capdevilla",
    "Maipú y Quintana",
    "Maipú y Granaderos",
    "Derqui y Gallo",
    "Derqui y Melo",
    "Derqui y M. Cane",
    "Derqui y Matheu",
    "Derqui y Pedernera",
    "Pedernera y B. Sur Mer",
    "Pedernera y Roldán",
    "Roldán y Lamadrid",
    "Roldán y Cerrito",
    "Cerrito y Collivadino",
    "Armesti y La Plata",
    "Armesti y Nueva York",
    "Armesti y Portugal",
    "Armesti y Nazaret",
    "Armesti y Suiza",
    "Armesti y Costa Rica",
    "Armesti y Monroe",
    "Armesti y El Litoral",
    "Armesti y Hungría",
    "Hungría y Baltazar",
    "Hungría Casuarinas",
    "Casuarinas y Yerbal",
    "Casuarinas y Moctezuma",
    "Casuarinas y Los Plátanos",
    "Casuarinas y L. Agote",
    "Casuarinas y Defensa",
    "Defensa y Baltasar",
    "Defensa y Armesti",
    "Armesti y Caaguazú",
    "Caaguazú y Lynch",
    "Caaguazú y Yapeyú",
    "Caaguazú e Ituzaingó",
    "Caaguazú y Tucumán",
    "Caaguazú y Monasterio",
    "Tucumán y Kloosterman",
    "Kloosterman y Sitio Montevideo",
    "Kloosterman y 9 de Julio",
    "9 de Julio y Chilavert",
    "9 de Julio y Chorroarín",
    "9 de Julio y Rondeau",
    "9 de Julio y Condarco",
    "9 de Julio y Corvalán",
    "9 de Julio y Cotagaita",
    "9 de Julio y Méndez",
    "9 de Julio y De la Peña",
    "9 de Julio y B. Italianos",
    "9 de Julio y Matanza",
    "9 de Julio y Chascomús",
    "9 de Julio y Magdalena",
    "9 de Julio y Centenario Uruguayo",
    "C. Uruguayo y Las Piedras",
    "C. Uruguayo y R. Cabrero",
    "R. Cabrero y Gral. Pico",
    "R. Cabrero y Posadas",
    "R. Cabrero y Oyuela",
    "R. Cabrero y H. de Malvinas",
    "R. Cabrero y Pedernera",
    "R. Cabrero y Suipacha",
    "R. Cabrero y Villa Luján",
    "R. Cabrero y M. Esquiú",
    "R. Cabrero y Madariaga",
    "R. Cabrero y Héctor Guidi",
    "R. Cabrero y Ferre",
    "Ferre y Las Piedras",
    "Ferre y 9 de Julio",
    "Ferre y Sitio Montevideo",
    "S. Montevideo y Córdoba",
    "S. Montevideo y Oncativo",
    "S. Montevideo y O’Higgins",
    "S. Montevideo y Sarmiento",
    "Estación Lanús"
  ],

  "264RJ": [
    "Estación Burzaco",
    "Rojas y Espora",
    "Espora y Alcorta",
    "Espora e Alem",
    "Espora e Italia",
    "Monteverde y Foppa",
    "Monteverde y Quiroga",
    "Monteverde y Rocha",
    "Monteverde y Buenos Aires",
    "Monteverde y Carlos Gardel",
    "Monteverde y Apecechea",
    "Monteverde y Montiel",
    "Monteverde y Martín Fierro",
    "Monteverde y Villafañe",
    "Monteverde y Martínez Paiva",
    "Monteverde y Lavardén",
    "Monteverde y E. del Campo",
    "Monteverde y Zelaya",
    "Monteverde y Figueroa",
    "Monteverde y L. de la Torre",
    "Monteverde y Eva Perón",
    "Monteverde y Trípodi",
    "Monteverde y Villegas",
    "Lacaze y Cavour",
    "Lacaze entre Garibaldi y Mazzini (Cotolengo)",
    "Lacaze y Dean Funes",
    "Lacaze y Juan José Paso",
    "Lacaze e Irupe",
    "Lacaze y Begonia",
    "Lacaze y Cala",
    "Lacaze y Azucena",
    "Lacaze y Margarita",
    "24 entre 857 y 857bis",
    "24 y 856",
    "24 y 854",
    "24 y 852",
    "24 y 849",
    "24 y 847",
    "847 y Donato",
    "Estación Solano",
    "Donato y 841",
    "Donato y 839",
    "Donato y 837",
    "Donato y 835",
    "Donato entre 832 y 833",
    "Donato y 831",
    "Donato y San Martín",
    "San Martín y 898",
    "San Martín y 895",
    "San Martín y 893",
    "San Martín y 891",
    "San Martín y 888",
    "San Martín y 886",
    "San Martín y 882",
    "San Martín y 878",
    "San Martín y 876",
    "San Martín y Camino",
    "Triunvirato y Camino",
    "Triunvirato y 392",
    "Triunvirato y 389",
    "Triunvirato y Alme Schiffely",
    "Triunvirato y Mosconi",
    "Triunvirato y Arg. Roca",
    "Triunvirato y Calchaquí",
    "Calchaquí e Irala",
    "Calchaquí y Amoedo",
    "12 de Octubre y Calchaquí",
    "12 de Octubre y Unamuno",
    "12 de Octubre y Acha",
    "12 de Octubre y L. de la Torre",
    "12 de Octubre y J.V. González",
    "12 de Octubre y Marconi",
    "12 de Octubre y Av. La Plata",
    "12 de Octubre y Condarco",
    "12 de Octubre y M. Rodríguez",
    "12 de Octubre y Blas Parera",
    "12 de Octubre y Urquiza",
    "12 de Octubre y Larrea",
    "12 de Octubre y Andrés Baranda",
    "12 de Octubre y B. Irigoyen",
    "12 de Octubre entre V. López y A. del Valle",
    "Olavarría y San Martín",
    "Irigoyen y Garibaldi",
    "Estación Quilmes",
    "Irigoyen y 9 de Julio",
    "Irigoyen y Colón",
    "Irigoyen y Alberdi",
    "Irigoyen y Saavedra",
    "Irigoyen y Castelli",
    "Irigoyen y San Lorenzo",
    "Irigoyen y Las Heras",
    "Pueyrredón y Carabelas",
    "Andrade y Reconquista",
    "Andrade y Monteagudo",
    "Andrade y Ascasubi",
    "Andrade y José López",
    "Andrade y Labardén",
    "Andrade y Dean Funes",
    "Roque Sáenz Peña y Carabelas",
    "Roque Sáenz Peña y Cramer",
    "José Manuel Estrada y Cramer",
    "Cramer y Almafuerte",
    "Constitución y Chiclana",
    "Constitución y Carabelas",
    "Constitución y Caseros",
    "Constitución y Fátima",
    "Lago Lacar y Ramella",
    "Lago Lacar y Victoria"
  ],
   "266R1":["Est. Lomas de Zamora", "Av. Alte. Brown Ayacucho","Junin y Pozos", "Cerrito y Zuviria",
    "Zuviria y Luis Saenz Peña", "Zuviria y Juncal"
   ]

  // Podés seguir agregando "266R1", "266R2", "266R4" con sus arrays de paradas
};
